# https://taskfile.dev

version: '3'

vars:
  # Constants
  TARGET_LIB_NAME: blurhash_ffi
  FRAMEWORK_NAME: blurhash_ffi
  # Archs
  IOS_SIM_TARGET_ARHS: ['x86_64-apple-ios', 'aarch64-apple-ios-sim']
  IOS_TARGET_ARHS: ['aarch64-apple-ios']
  MACOS_TARGET_ARHS: ['aarch64-apple-darwin', 'x86_64-apple-darwin']
  # Utils
  EXTENSION_LIB: '{{if eq OS "windows"}}dll{{else if eq OS "darwin"}}dylib{{else}}so{{end}}'

tasks:
  generate:bindings:
    desc: Generate the bindings for the native Rust code
    dir: rust
    cmds:
      - cbindgen --config cbindgen.toml --crate blurhash-ffi --output ../ios/Classes/{{.TARGET_LIB_NAME}}.h
  
  generate:ffi:
    desc: Generate the FFI bindings for the native Rust code
    cmds:
      - flutter pub run ffigen --config ffigen.yaml

  generate:all:
    desc: Generate all files
    cmds:
      - task: generate:bindings
      - task: generate:ffi

  build:clean:
    desc: Clean build folders
    dir: rust
    cmds:
      - cargo clean
  # copy-file:
  #   desc: Coping the file to destination folder
  #   internal: true
  #   vars:
  #     FROM_FOLDER: '{{default "pkg" .FROM_FOLDER}}'
  #     TO_FOLDER: '{{default "bin" .TO_FOLDER}}'
  #     FILE: '{{default "blurhash_ffi_bg.wasm" .FILE}}'
  #     # Constant variables
  #     FILE_NAME: '{{trimSuffix (printf ".%s" .FILE_EXTENSION) .FILE}}'
  #     FILE_EXTENSION: '{{last (splitList "." .FILE)}}'
  #     CMD_COPY: '{{if eq OS "windows"}}copy{{else}}cp{{end}}'
  #     CMD_RENAME: '{{if eq OS "windows"}}ren{{else}}mv{{end}}'
  #   cmds:
  #     - cmd: '{{.CMD_COPY}} {{.FROM_FOLDER}}/{{.FILE}} {{.TO_FOLDER}}/{{.FILE}} &&
  #             {{.CMD_RENAME}} {{.TO_FOLDER}}/{{.FILE}} {{.TO_FOLDER}}/{{.TARGET_LIB_NAME}}.{{.FILE_EXTENSION}}'
  
  copy-folder:
    desc: Coping the folder to destination folder
    internal: true
    preconditions:
      - sh: '{{if env "FROM_FOLDER" }} exit 1 {{end}}'
        msg: 'Variable `FROM_FOLDER` is required'
      - sh: '{{if env "TO_FOLDER" }} exit 1 {{end}}'
        msg: 'Variable `TO_FOLDER` is required'
      - sh: '{{if env "DELETE_FOLDER" }} exit 1 {{end}}'
        msg: 'Variable `DELETE_FOLDER` is required'
    vars:
      # Constant variables
      CMD_COPY: '{{if eq OS "windows"}}xcopy{{else}}cp -R{{end}}'
      CMD_REMOVE: '{{if eq OS "windows"}}rmdir /s /q{{else}}rm -rf{{end}}'
    cmds:
      - cmd: '{{ if .DELETE_FOLDER }}{{$.CMD_REMOVE}} {{$.TO_FOLDER}} {{else}} echo "Coping without deletion" {{end}}'
      - cmd: '{{.CMD_COPY}} {{.FROM_FOLDER}} {{.TO_FOLDER}} {{if eq OS "windows"}}/E /I /Y{{end}}'

  build:wasm:
    desc: Build the WASM code in release mode
    dir: rust
    cmds:
      - wasm-pack build --release --target web
      - task: copy-file
        vars:
          FROM_FOLDER: pkg
          TO_FOLDER: ../web/assets
          FILE: '{{.TARGET_LIB_NAME}}_bg.wasm'

  build:ios:
    desc: Build for iOS targets.
    dir: rust
    platforms: [darwin]
    vars:
      IOS_ARCHS: '{{ concat .IOS_TARGET_ARHS .IOS_SIM_TARGET_ARHS }}'
    cmds:                                                                                                             
      - for: { var: IOS_ARCHS, as: ARCH }
        cmd: cargo build --lib --release --target {{.ARCH | replace "[" "" | replace "]" ""}}
      - for: { var: IOS_ARCHS, as: ARCH }
        cmd: rm -rf ../ios/Libraries/lib{{.TARGET_LIB_NAME}}-{{ splitList "-" .ARCH | last | replace "[" "" | replace "]" ""}}.a
      - mkdir -p ../ios/Libraries/ios
      - for: { var: IOS_TARGET_ARHS, as: ARCH }
        cmd: cp target/{{.ARCH}}/release/lib{{.TARGET_LIB_NAME}}.a ../ios/Libraries/ios/lib{{.TARGET_LIB_NAME}}-{{ splitList "-" .ARCH | last | replace "[" "" | replace "]" ""}}.a
      - 'lipo -create -output ../ios/Libraries/ios/lib{{.TARGET_LIB_NAME}}-sim.a {{range $arch := .IOS_SIM_TARGET_ARHS}}target/{{$arch}}/release/lib{{$.TARGET_LIB_NAME}}.a {{end}}'
      - lipo -info ../ios/Libraries/ios/lib{{.TARGET_LIB_NAME}}-ios.a 

  build:macos:
    desc: Build for macOs targets.
    dir: rust
    platforms: [darwin]
    cmds:
      - for: { var: MACOS_TARGET_ARHS, as: ARCH }
        cmd: cargo build --lib --release --target {{.ARCH}}
      - mkdir -p ../ios/Libraries/macos
      - rm -rf ../ios/Libraries/macos/lib{{.TARGET_LIB_NAME}}-macos.a
      - 'lipo -create -output ../ios/Libraries/macos/lib{{.TARGET_LIB_NAME}}-macos.a {{range $arch := .MACOS_TARGET_ARHS}}target/{{$arch}}/release/lib{{$.TARGET_LIB_NAME}}.a {{end}}'
      - lipo -info ../ios/Libraries/macos/lib{{.TARGET_LIB_NAME}}-macos.a

  bootstrap:
    desc: Build for all.
    aliases: [bs]
    cmds:
      # Darwin targets
      - task: precheck:all
      - task: generate:bindings
      - task: generate:ffi
      - task: build:ios
      - task: build:macos
      # - task: copy-folder
      #   vars:
      #     FROM_FOLDER: rust/bin/{{.FRAMEWORK_NAME}}.xcframework
      #     TO_FOLDER: ios/Frameworks/{{.FRAMEWORK_NAME}}.xcframework
      #     DELETE_FOLDER: true
    
        
      # - for: { var: MACOS_TARGET_ARHS, as: ARCH }
      #   cmd: cargo build --release --lib --target {{.ARCH}}
      #   platforms: [darwin]
      # - task: copy-file
      #   vars:
      #     FROM_FOLDER: target/release/aarch64-apple-ios
      #     TO_FOLDER: bin/aarch64-apple-ios
      #     FILE: libblurhash_ffi.a

  precheck:rust-targets:
    desc: Downloading Rust comaptible targets.
    dir: rust
    vars:
      DARWIN_TARGETS: '{{ concat .IOS_TARGET_ARHS .IOS_SIM_TARGET_ARHS .MACOS_TARGET_ARHS }}'
    cmds:
      - for: { var: DARWIN_TARGETS, as: TARGET }
        cmd: rustup target add {{.TARGET | replace "[" "" | replace "]" ""}}
        platforms: [darwin]

  precheck:all:
    desc: All precheck required dependencies.
    cmds:
      - task: precheck:rust-targets