// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `rust/include/blurhash_ffi.h`.
///
/// Regenerate bindings with `flutter pub run ffigen --config ffigen.yaml`.
///
class BlurhashFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BlurhashFfiBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BlurhashFfiBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Char> blurhash_encode(
    int components_x,
    int components_y,
    int width,
    int height,
    ffi.Pointer<ffi.Uint8> rgba_image,
    int rgba_image_len,
  ) {
    return _blurhash_encode(
      components_x,
      components_y,
      width,
      height,
      rgba_image,
      rgba_image_len,
    );
  }

  late final _blurhash_encodePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Uint32,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Pointer<ffi.Uint8>,
              ffi.UintPtr)>>('blurhash_encode');
  late final _blurhash_encode = _blurhash_encodePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          int, int, int, int, ffi.Pointer<ffi.Uint8>, int)>();

  ffi.Pointer<ffi.Uint8> blurhash_decode(
    ffi.Pointer<ffi.Uint8> blurhash,
    int blurhash_len,
    int width,
    int height,
    double punch,
  ) {
    return _blurhash_decode(
      blurhash,
      blurhash_len,
      width,
      height,
      punch,
    );
  }

  late final _blurhash_decodePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Uint8> Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr,
              ffi.Uint32, ffi.Uint32, ffi.Float)>>('blurhash_decode');
  late final _blurhash_decode = _blurhash_decodePtr.asFunction<
      ffi.Pointer<ffi.Uint8> Function(
          ffi.Pointer<ffi.Uint8>, int, int, int, double)>();

  bool is_valid_blurhash(
    ffi.Pointer<ffi.Uint8> blurhash,
    int blurhash_len,
  ) {
    return _is_valid_blurhash(
      blurhash,
      blurhash_len,
    );
  }

  late final _is_valid_blurhashPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(
              ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>>('is_valid_blurhash');
  late final _is_valid_blurhash = _is_valid_blurhashPtr
      .asFunction<bool Function(ffi.Pointer<ffi.Uint8>, int)>();

  void free_string(
    ffi.Pointer<ffi.Char> ptr,
  ) {
    return _free_string(
      ptr,
    );
  }

  late final _free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'free_string');
  late final _free_string =
      _free_stringPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void free_decoded_data(
    ffi.Pointer<ffi.Uint8> ptr,
    int len,
  ) {
    return _free_decoded_data(
      ptr,
      len,
    );
  }

  late final _free_decoded_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>>('free_decoded_data');
  late final _free_decoded_data = _free_decoded_dataPtr
      .asFunction<void Function(ffi.Pointer<ffi.Uint8>, int)>();

  late final addresses = _SymbolAddresses(this);
}

class _SymbolAddresses {
  final BlurhashFfiBindings _library;
  _SymbolAddresses(this._library);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>
      get free_string => _library._free_stringPtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>>
      get free_decoded_data => _library._free_decoded_dataPtr;
}
